
import 'package:firebase_core/firebase_core.dart';
import 'package:deluxe/firebase_options.dart'; // This file is generated by the FlutterFire CLI

/// Initializes Firebase using the platform-specific options.
///
/// This function is called from `main.dart` before the app is run.
Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
